#
# Libc Makefile
#

# libc
libc += libgen.c

# libc/builtins
libc += builtins/divdi3.s \
	builtins/udivdi3.s

# libc/math
libc += math/math.c

# libc/stdio
libc += stdio/printf.c \
	stdio/stdio.c

# libc/stdlib
libc += stdlib/stdlib.c

# libc/string
libc += string/string.c
