#
# Libc Makefile
#

# libc
libc += libgen.c

# libc/math
libc += math/math.c

# libc/stdio
libc += stdio/printf.c \
	stdio/stdio.c

# libc/stdlib
libc += stdlib/stdlib.c

# libc/string
libc += string/string.c


# libc-y
libc-y = $(call objects,libc,$(BUILD_DIR)/libc)
