# Drivers sources
$(call register,drivers,KERNEL)

# drivers/
drivers += framebuf.c memory.c ramdisk.c

# drivers/tty
drivers += tty/uart.c

# drivers/usb/hid
drivers += usb/hid/hid.c \
	usb/hid/hid-report.c usb/hid/hid-usage.c \
	usb/hid/keyboard.c usb/hid/mouse.c

# drivers/usb/host
drivers += usb/host/xhci.c

# drivers/usb/msd
drivers += usb/msd/scsi.c
